### ISSUE TITLE
响应参数是如何配置的

### ISSUE THREAD

**Issue by DavidWuJay** [DoveAz/nest-knife4j#4]
按照swagger 响应参数已经是有返回 可是knife4j不展示响应参数

**Comment by DoveAz** [comment]
根本显示不了😅 我已经弃坑了，建议使用apifox #3

**Comment by shi-lai-mu** [comment]
> 根本显示不了😅 我已经弃坑了，建议使用apifox #3

0.03还是正常的，0.04只有post的不正常，应该还是能修复的吧？

**Comment by shi-lai-mu** [comment]
> 根本显示不了😅 我已经弃坑了，建议使用apifox #3
我这边自己编译改了一下是正常显示的
![image](https://user-images.githubusercontent.com/45140991/177461865-77dcf561-f8a1-4682-836f-c375ec8056be.png)
<img width="689" alt="image" src="https://user-images.githubusercontent.com/45140991/177461904-a226e860-3ae5-487f-af87-49edbd9ffa7d.png">

**Comment by DoveAz** [comment]
> > 根本显示不了😅 我已经弃坑了，建议使用apifox #3
> > 我这边自己编译改了一下是正常显示的
> > ![image](https://user-images.githubusercontent.com/45140991/177461865-77dcf561-f8a1-4682-836f-c375ec8056be.png)
> 
> <img alt="image" width="689" src="https://user-images.githubusercontent.com/45140991/177461904-a226e860-3ae5-487f-af87-49edbd9ffa7d.png">

老哥666🐂🍺

**Comment by DoveAz** [comment]
已修复
