### ISSUE TITLE
参数多级嵌套无法显示

### ISSUE THREAD

**Issue by icjking** [DoveAz/nest-knife4j#5]
您好，多级参数无法显示，以下是需要回显的DTO

```typescript
export class PaginatedDto<T = any> {

  @ApiProperty({
	description: '数据列表，默认空数组',
	default: [],
  })
  records: T[];

  @ApiProperty()
  total: number;

  @ApiProperty()
  pageIndex?: number;

  @ApiProperty()
  pageSize?: number;
}

export class BasicPaginatedResponseDto<T = any> {
  @ApiProperty({
	description: '状态码',
	default: 200,
  })
  code: number;

  @ApiProperty({
	description: '消息描述',
  })
  message: string;

  @ApiProperty({
	description: '分页对象',
  })
  @ValidateNested()
  @Type(() => PaginatedDto<T>)
  result: PaginatedDto<T>;
}
```

NestJs 版本：9.3.12

现在状态：
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/7961076/230590324-7dee6db7-54fe-4682-b5eb-fa2e9b6eaf77.png">

期望结果：
<img width="624" alt="image" src="https://user-images.githubusercontent.com/7961076/230590213-f0f2a1c2-412c-4760-9493-f1610d3e8b91.png">

**Comment by icjking** [comment]
解决方案：

```ts
@ApiProperty({ type: () => PaginatedDto<T> })
result: PaginatedDto<T>;
```

参照官方文档：
<img width="845" alt="image" src="https://user-images.githubusercontent.com/7961076/232372947-6cbd6171-c432-4aaa-9720-428027443763.png">

**Comment by Groupguanfang** [comment]
我用的是allOf参数，虽然循环依赖也可以，但是循环依赖没法重复使用。
但是，但是，这个knife4j无法识别allOf，就很蛋疼
![image](https://user-images.githubusercontent.com/64218589/232498404-cbc0da72-8857-4550-9d2c-59bdaca7987f.png)
